### ISSUE TITLE
akka 2.5

### ISSUE THREAD

**Issue by pjfanning** [kamon-io/kamon-akka#11]
It looks like kamon-akka-2.4 works with akka 2.5.0. Are there any plans to issue a specific kamon-akka-2.5 or is this unnecessary?
One proviso is that akka-http 10.0.5 is needed for akka 2.5.0. So it might be worth updating the kamon-akka-http dependency on akka-http to 10.0.5.
https://github.com/pjfanning/kamon-akka-group demonstrates a simple sample that uses akka 2.5.0 and kamon-akka-2.4 together.

**Comment by thjaeckle** [comment]
When using Kamon with Akka 2.5 there is at least one Exception on graceful shutdown of an ActorSystem:
```
14:53:02.704 SERVICE> Detected java.lang.NoSuchMethodError error, which MAY be caused by incompatible Akka versions on the classpath. Please note that a given Akka version MUST be the same across all modules of Akka that you are using, e.g. if you use akka-actor [2.5.1 (resolved from current classpath)] all other core Akka modules MUST be of the same version. External projects like Alpakka, Persistence plugins or Akka HTTP etc. have their own version numbers - please make sure you're using a compatible set of libraries.
14:53:02.707 SERVICE> [ERROR] [SECURITY][05/22/2017 12:53:02.706] [cluster-akka.actor.default-dispatcher-19] [akka.actor.ActorSystemImpl(cluster)] Uncaught error from thread [cluster-akka.actor.default-dispatcher-19] shutting down JVM since 'akka.jvm-exit-on-fatal-error' is enabled
14:53:02.707 SERVICE> Uncaught error from thread [cluster-akka.actor.default-dispatcher-19] shutting down JVM since 'akka.jvm-exit-on-fatal-error' is enabled for ActorSystem[cluster]
14:53:02.707 SERVICE> java.lang.NoSuchMethodError: akka.actor.ActorSystem.shutdown()V
14:53:02.707 SERVICE> at kamon.Kamon$.shutdown(Kamon.scala:61)
14:53:02.707 SERVICE> at kamon.Kamon.shutdown(Kamon.scala)
14:53:02.708 SERVICE> at akka.actor.ActorSystemImpl$TerminationCallbacks$$anonfun$addRec$1$1.applyOrElse(ActorSystem.scala:973)
14:53:02.708 SERVICE> at akka.actor.ActorSystemImpl$TerminationCallbacks$$anonfun$addRec$1$1.applyOrElse(ActorSystem.scala:973)
14:53:02.708 SERVICE> at scala.concurrent.Future$$anonfun$andThen$1.apply(Future.scala:436)
14:53:02.708 SERVICE> at scala.concurrent.Future$$anonfun$andThen$1.apply(Future.scala:435)
14:53:02.708 SERVICE> at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:36)
14:53:02.708 SERVICE> at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:55)
14:53:02.708 SERVICE> at akka.dispatch.BatchingExecutor$BlockableBatch$$anonfun$run$1.apply$mcV$sp(BatchingExecutor.scala:91)
14:53:02.708 SERVICE> at akka.dispatch.BatchingExecutor$BlockableBatch$$anonfun$run$1.apply(BatchingExecutor.scala:91)
14:53:02.708 SERVICE> at akka.dispatch.BatchingExecutor$BlockableBatch$$anonfun$run$1.apply(BatchingExecutor.scala:91)
14:53:02.708 SERVICE> at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:72)
14:53:02.708 SERVICE> at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:90)
14:53:02.708 SERVICE> at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:38)
14:53:02.708 SERVICE> at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:43)
14:53:02.708 SERVICE> at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
14:53:02.709 SERVICE> at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
14:53:02.709 SERVICE> at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
14:53:02.709 SERVICE> at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
```

**Comment by pjfanning** [comment]
The latest kamon-core code has an abstraction for the actor-system terminate.
https://github.com/kamon-io/Kamon/blob/master/kamon-core/src/main/scala/kamon/Kamon.scala

**Comment by ivantopo** [comment]
I'll get to this later today!

**Comment by dpsoft** [comment]
@pjfanning @ivantopo @thjaeckle this issue is related to https://github.com/kamon-io/Kamon/pull/460?

**Comment by pjfanning** [comment]
I think we should merge https://github.com/kamon-io/Kamon/pull/460 - I've requested a small mod to the change though.

**Comment by thjaeckle** [comment]
@dpsoft yes, it is related, but that was only one obvious thing not working with Akka 2.5 - I can't oversee yet if Kamon 0.6.6 (compiled against Akka 2.4) works with Akka 2.5

**Comment by ivantopo** [comment]
@thjaeckle please let us know if you see any issues :)

**Comment by dpsoft** [comment]
@pjfanning @thjaeckle we just released a new snapshot version in our bintray repository `0.6.7-f50a47658f5dfe4c2718cd88ed934d138f5fdc31` ;)

**Comment by thjaeckle** [comment]
looks good so far apart from the `shutdown()`
do you have plans for a release? using a snapshot in production probably is not such a good idea :)

**Comment by dpsoft** [comment]
@pjfanning @thjaeckle we just released a new release version in our bintray repository 0.6.7.

**Comment by lukasz-golebiewski** [comment]
Guys, what about other modules like e.g. https://bintray.com/kamon-io/releases/kamon-akka-remote ? Are they also going to be released to bintray any time soon?

**Comment by pjfanning** [comment]
I have noticed an issue when using akka 2.5. Akka 2.5 seems to have a new akka.dispatch.forkjoin.ForkJoinPool class and kamon-akka DispatcherInstrumentation does not not support it.

**Comment by dpsoft** [comment]
fixed with: https://github.com/kamon-io/kamon-akka/commit/5a81f299092119fb1705d9762e4bab33b0c1b873
