### ISSUE TITLE
Support for `Akka 2.6.0`

### ISSUE THREAD

**Issue by taeguk** [kamon-io/kamon-akka#62]
Akka 2.6.0 was released and current `kamon-akka` doesn't works on `akka 2.6.0`.

One breaking change is that `akka.dispatch.ForkJoin` was removed. (https://doc.akka.io/docs/akka/current/project/migration-guide-2.5.x-2.6.x.html#akka-now-uses-fork-join-pool-from-jdk)
So, `Exception in thread "main" java.lang.NoClassDefFoundError: akka/dispatch/forkjoin/ForkJoinPool` exception occurs.

**Comment by ivantopo** [comment]
Hey @taeguk,

I started working on this.. there are a couple more issues. Thanks for raising the issue!

**Comment by narma** [comment]
Great news! It will be great to have new release with this fix, as well for `kamon-bundle` which bundle `kamon-akka` itself.

**Comment by taeguk** [comment]
Thanks!

**Comment by ryanb93** [comment]
@ivantopo any idea when `kamon-bundle` will be updated to support the latest version?

**Comment by miguelemosreverte** [comment]
Same question over here

**Comment by miguelemosreverte** [comment]
@ivantopo Hey, how you doin?!

Our team is following intently your work, we wanted to ask you how things are turning aroung, is Akka 2.6 support going to become a reality during the following weeks or months?

**Comment by nicolasdalsass** [comment]
@miguelemosreverte I'm not the maintainer, but akka 2.6 support has been released in v2.0.1 (hence why the issue is closed).
